### ISSUE TITLE
cannot connect to heroku postgresql

### ISSUE THREAD

**Issue by lucidfrontier45** [mfenniak/pg8000#111]
`psycopg2` can connect to heroku postgresql correctly.
The following is the exception trace. (user, password ... is dummy)
I used the free postgresql plan with default settings.

``` python
pg8000.connect(user="esjrrekl", password="slkdsjekrj", host="ec2-23o4ewjrwor.compute-1.amazonaws.com", port=5432, database="skerjeslrjew")
---------------------------------------------------------------------------
InterfaceError                            Traceback (most recent call last)
<ipython-input-2-d7d6372c1060> in <module>()
----> 1 pg8000.connect(user="gtclqsmxooouab", password="ZzcUrl0v0T5W2tGBbwI7M4ww6Q", host="ec2-54-235-202-71.compute-1.amazonaws.com", port=5432, database="ddb3pmlmlr886v")

/home/du/.conda/envs/anaconda/lib/python3.5/site-packages/pg8000/__init__.py in connect(user, host, unix_sock, port, database, password, ssl, timeout, **kwargs)
    101     """
    102     return Connection(
--> 103         user, host, unix_sock, port, database, password, ssl, timeout)
    104 
    105 apilevel = "2.0"

/home/du/.conda/envs/anaconda/lib/python3.5/site-packages/pg8000/core.py in __init__(self, user, host, unix_sock, port, database, password, ssl, timeout)
   1610                 except Exception:
   1611                     pass
-> 1612                 raise e
   1613 
   1614         self.in_transaction = False

/home/du/.conda/envs/anaconda/lib/python3.5/site-packages/pg8000/core.py in __init__(self, user, host, unix_sock, port, database, password, ssl, timeout)
   1604                     self.message_types[code](self._read(data_len - 4), None)
   1605                 if self.error is not None:
-> 1606                     raise self.error
   1607             except Exception as e:
   1608                 try:

InterfaceError: md5 password authentication failed
```

**Comment by mfenniak** [comment]
Hm, I'm not really sure what this could be.  What I'd suggest doing if you want to resolve this is to modify your pg8000 @ https://github.com/mfenniak/pg8000/blob/cd4e1e96184f61cefa7ecb00b2fc88062aa65e5f/pg8000/core.py#L1624.  At this point if pg8000 receives a specific error code from Postgres, it replaces the error with the exception you're seeing -- I'd suggest disabling this and letting the "else" clause run instead.  This might throw an error that would have more specific details that have been provided by the Postgres host, which could illuminate what the problem is.

**Comment by tlocke** [comment]
Hi @lucidfrontier45 pg8000 definitely supports md5 authentication. This is the error message that you'd get if the password was incorrect. I'm sure you've checked the password, so there could be a bug in pg8000. Here are some questions:

* Is there anything helpful in the postgres server error log?
* What version of Python are you running?
* What version of Postgres are you running?
* Are the username, password and database name all within the ASCII character set?
* What's the character_encoding of the database set to? (you can just do 'show character_encoding;' is psql).

**Comment by lucidfrontier45** [comment]
@tlocke 
The point is, `psycopg2` or simply using `psql` command didn't gives this error.

Here is my test heroku postgresql and test codes.

```python
import sqlalchemy as sa
url = 'postgresql+{}://gtclqsmxooouab:ZzcUrl0v0T5W2tGBbwI7M4ww6Q@ec2-54-235-202-71.compute-1.amazonaws.com:5432/ddb3pmlmlr886v'

engine_psycopg2 = sa.create_engine(url.format("psycopg2"))
engine_pg8000 = sa.create_engine(url.format("pg8000"))

# OK
engine_psycopg2.connect()

# InterfaceError: (pg8000.core.InterfaceError) md5 password authentication failed
engine_pg8000.connect()
```

**Comment by tlocke** [comment]
Okay, there was a bug in how we were dealing with the password when it was outside the ASCII character set. It may not be causing your problem though because your password was within ASCII, but I've fixed it anyway and done a new release of pg8000, 1.10.6. Could you try this new release please? If it doesn't work, let me know and we'll get to work narrowing down the problem!

**Comment by lucidfrontier45** [comment]
@tlocke 

Thank you for the fix. However, it still gives  `md5 password authentication failed`

**Comment by lucidfrontier45** [comment]
I followed @mfenniak and the exact exception was 

```python
/home/du/.virtualenvs/test/lib/python3.5/site-packages/pg8000/core.py in __init__(self, user, host, unix_sock, port, database, password, ssl, timeout)
   1604                     self.message_types[code](self._read(data_len - 4), None)
   1605                 if self.error is not None:
-> 1606                     raise self.error
   1607             except Exception as e:
   1608                 try:

ProgrammingError: (pg8000.core.ProgrammingError) ('FATAL', '28000', 'no pg_hba.conf entry for host "126.42.122.85", user "gtclqsmxooouab", database "ddb3pmlmlr886v", SSL off', 'auth.c', '467', 'ClientAuthentication', '', '')
```

Looks like its about the SSL. Still I don't know why psycopg2 is OK while pg8000 gives error.

**Comment by mfenniak** [comment]
I believe Heroku Postgers does require SSL, as it is a remote service accessed without an otherwise secure network.  Can you add ssl=True to your connection options, and see whether that works?

**Comment by mfenniak** [comment]
I think it's possible for the driver to negotiate / learn whether ssl is required during the handshake phase; my guess would be that's something that isn't currently supported by pg8000, while it might be supported by psycopg2.

**Comment by tlocke** [comment]
As an aside I thought your suggestion was brilliant @mfenniak, so I've pushed [a commit](https://github.com/mfenniak/pg8000/commit/9dfad86f4caab48e303f464dae1966d698a92ffa) that always allows the full error through rather than putting in our own text.

**Comment by tlocke** [comment]
This is a bit old now, so I'm closing it.

**Comment by vaab** [comment]
Still an issue in 1.3.1 ... we had same issue with a connection url that would work on `psycopg2` engine, and not on `pg8000`, on our side, using `?ssl=true` at the end of the connection url will make `pg8000` connect. We are coming from recent version of `zato`, and a mis-feature of the later allows us to append `?ssl=true` to the database name to get it tuck at the end of the connection url and allow our script to connect.

Added this info just in case somebody falls on this bug report and is looking for a workaround.

**Comment by tlocke** [comment]
Hi @vaab, this repository isn't used anymore, but I've raised an issue in the current repository https://github.com/tlocke/pg8000/issues/160
